# Form implementation generated from reading ui file 'ui_kandinsky_widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KandinskyWidget(object):
    def setupUi(self, KandinskyWidget):
        KandinskyWidget.setObjectName("KandinskyWidget")
        KandinskyWidget.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(KandinskyWidget)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apikey_label = QtWidgets.QLabel(parent=KandinskyWidget)
        self.apikey_label.setObjectName("apikey_label")
        self.horizontalLayout.addWidget(self.apikey_label)
        self.apikey_lineedit = QtWidgets.QLineEdit(parent=KandinskyWidget)
        self.apikey_lineedit.setObjectName("apikey_lineedit")
        self.horizontalLayout.addWidget(self.apikey_lineedit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=KandinskyWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.apisecret_lineedit = QtWidgets.QLineEdit(parent=KandinskyWidget)
        self.apisecret_lineedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.apisecret_lineedit.setObjectName("apisecret_lineedit")
        self.horizontalLayout_3.addWidget(self.apisecret_lineedit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.styles_group_box = QtWidgets.QGroupBox(parent=KandinskyWidget)
        self.styles_group_box.setObjectName("styles_group_box")
        self.verticalLayout_3.addWidget(self.styles_group_box)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.negative_prompt_label = QtWidgets.QLabel(parent=KandinskyWidget)
        self.negative_prompt_label.setObjectName("negative_prompt_label")
        self.horizontalLayout_2.addWidget(self.negative_prompt_label)
        self.negative_prompt_lineedit = QtWidgets.QLineEdit(parent=KandinskyWidget)
        self.negative_prompt_lineedit.setObjectName("negative_prompt_lineedit")
        self.horizontalLayout_2.addWidget(self.negative_prompt_lineedit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.prompt_label = QtWidgets.QLabel(parent=KandinskyWidget)
        self.prompt_label.setObjectName("prompt_label")
        self.verticalLayout.addWidget(self.prompt_label)
        self.prompt_lineedit = QtWidgets.QPlainTextEdit(parent=KandinskyWidget)
        self.prompt_lineedit.setDocumentTitle("")
        self.prompt_lineedit.setPlaceholderText("")
        self.prompt_lineedit.setObjectName("prompt_lineedit")
        self.verticalLayout.addWidget(self.prompt_lineedit)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(KandinskyWidget)
        QtCore.QMetaObject.connectSlotsByName(KandinskyWidget)

    def retranslateUi(self, KandinskyWidget):
        _translate = QtCore.QCoreApplication.translate
        KandinskyWidget.setWindowTitle(_translate("KandinskyWidget", "Kandinsky API Configuration"))
        self.apikey_label.setText(_translate("KandinskyWidget", "API Key"))
        self.label.setText(_translate("KandinskyWidget", "API Secret"))
        self.styles_group_box.setTitle(_translate("KandinskyWidget", "Select style"))
        self.negative_prompt_label.setText(_translate("KandinskyWidget", "Negative prompt"))
        self.prompt_label.setText(_translate("KandinskyWidget", "Prompt"))
