# Form implementation generated from reading ui file 'ui_kandinsky_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KandinskyWidget(object):
    def setupUi(self, KandinskyWidget):
        KandinskyWidget.setObjectName("KandinskyWidget")
        KandinskyWidget.resize(400, 300)
        KandinskyWidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(33, 33, 33);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: white;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    color: white;\n"
"    font: 11pt \"Inter\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: white;\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       #46A229;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(48, 48, 48);\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(KandinskyWidget)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.apikey_label = QtWidgets.QLabel(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        self.apikey_label.setFont(font)
        self.apikey_label.setObjectName("apikey_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.apikey_label)
        self.apikey_lineedit = QtWidgets.QLineEdit(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.apikey_lineedit.setFont(font)
        self.apikey_lineedit.setObjectName("apikey_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.apikey_lineedit)
        self.apisecret_lineedit = QtWidgets.QLineEdit(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.apisecret_lineedit.setFont(font)
        self.apisecret_lineedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.apisecret_lineedit.setObjectName("apisecret_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.apisecret_lineedit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.styles_group_box = QtWidgets.QGroupBox(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.styles_group_box.setFont(font)
        self.styles_group_box.setObjectName("styles_group_box")
        self.verticalLayout_3.addWidget(self.styles_group_box)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.negative_prompt_label = QtWidgets.QLabel(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        self.negative_prompt_label.setFont(font)
        self.negative_prompt_label.setObjectName("negative_prompt_label")
        self.horizontalLayout_2.addWidget(self.negative_prompt_label)
        self.negative_prompt_lineedit = QtWidgets.QLineEdit(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.negative_prompt_lineedit.setFont(font)
        self.negative_prompt_lineedit.setObjectName("negative_prompt_lineedit")
        self.horizontalLayout_2.addWidget(self.negative_prompt_lineedit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.prompt_label = QtWidgets.QLabel(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(False)
        self.prompt_label.setFont(font)
        self.prompt_label.setObjectName("prompt_label")
        self.verticalLayout.addWidget(self.prompt_label)
        self.prompt_lineedit = QtWidgets.QPlainTextEdit(parent=KandinskyWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.prompt_lineedit.setFont(font)
        self.prompt_lineedit.setDocumentTitle("")
        self.prompt_lineedit.setPlaceholderText("")
        self.prompt_lineedit.setObjectName("prompt_lineedit")
        self.verticalLayout.addWidget(self.prompt_lineedit)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(KandinskyWidget)
        QtCore.QMetaObject.connectSlotsByName(KandinskyWidget)

    def retranslateUi(self, KandinskyWidget):
        _translate = QtCore.QCoreApplication.translate
        KandinskyWidget.setWindowTitle(_translate("KandinskyWidget", "Kandinsky API Configuration"))
        self.label.setText(_translate("KandinskyWidget", "API Secret"))
        self.apikey_label.setText(_translate("KandinskyWidget", "API Key"))
        self.styles_group_box.setTitle(_translate("KandinskyWidget", "Select style"))
        self.negative_prompt_label.setText(_translate("KandinskyWidget", "Negative prompt"))
        self.prompt_label.setText(_translate("KandinskyWidget", "Prompt"))
